Fix: Chip Icon
openpolitica/open-wizard pull request #167
Opened 2021-02-22 03:58 UTC by paulclindo

Closes https://github.com/openpolitica/open-wizard/issues/106

![Screen Shot 2021-02-21 at 10 56 15 PM](https://user-images.githubusercontent.com/46382556/108656592-03a61880-7498-11eb-8270-5c222878f060.png)

2021-02-22 07:01 UTC, wixo requested changes
Gracias @paulclindo por enviar tus primeros PRs! hay unos cambios que estoy pidiendo y unas preguntas sobre la solución. Consideras que futuros svgs necesitarían ser editados como se han hecho ahora para que sean compatibles con esta solución? En líneas generales me parece interesante pero me pregunto que cosas se tienen que hacer para que funcione con futuros íconos también. 🙌

2021-02-22 07:01 UTC, wixo commented on components/Chip/styles.js
> +export const WrapperImg = styled('div')`
De repente podríamos llamarle `ChipCanvas`? porque entiendo que sería el lienzo que envuelve al ícono.

2021-02-22 07:01 UTC, wixo commented on components/Chip/styles.js
> +  position: relative;
Estamos tratando de mantener el orden de las propiedades en orden alfabético, para que sea más fácil de encontrar en el futuro.

2021-02-22 07:01 UTC, wixo commented on components/Chip/styles.js
> +    <Image layout="fill" objectFit="cover" {...props} />
Interesante, crees que esta solución es replicable para futuros íconos?

2021-02-22 07:01 UTC, wixo commented on components/Chip/styles.js
> -  gap: 0.75rem;
Esto como afecta al resto de instancias? No me queda claro como lo estamos suplantando.

2021-02-23 07:12 UTC, paulclindo commented on components/Chip/styles.js
> -  gap: 0.75rem;
Agregue un margin right en el div wrapper del Icono ` margin-right: 0.5rem;` en el caso de que el icono luego sea optional. 
https://github.com/paulclindo/open-wizard/blob/cda88ea0ba4fa7c84c3526adcd8a61e15210457f/components/Chip/styles.js#L8

Y no afectaría en nada, solo que el Flexbox gap aun no esta soportado por Safari (e incluso en Chrome no es muy estable)

2021-02-23 07:23 UTC, paulclindo commented
@wixo Fixed it! Sobre los iconos, deberíamos mantener un viewBox estándar, en este caso tome 22 x 22 ya que así lo encontré en los mockups del Figma, solo que al momento de copiar los svgs me parece que solo seleccionaron el path y no su toda la caja donde se dibuja el svg. 
Entonces siempre los iconos deberían estar dibujados en un lienzo de 22 x 22 y al momento de copiar los svgs asegurar que estamos copiando todo ese lienzo. 🙌   
![Screen Shot 2021-02-23 at 2 20 20 AM](https://user-images.githubusercontent.com/46382556/108812750-aedccd80-757d-11eb-905c-c46755733c73.png)

2021-02-24 07:04 UTC, wixo approved these changes
Gracias! @paulclindo ✅

2021-02-24 07:04 UTC, merged