add border based on the active step
openpolitica/open-wizard pull request #168
Opened 2021-02-22 04:37 UTC by paulclindo

Closes https://github.com/openpolitica/open-wizard/issues/24

<img src="https://user-images.githubusercontent.com/46382556/108663014-92696400-749d-11eb-9289-29310fb26ae7.gif" width="500px" />

2021-02-22 06:55 UTC, wixo requested changes
Hola @paulclindo, gracias por enviar este PR, te dejo un par de comentarios, para que los revises.

2021-02-22 06:55 UTC, wixo commented on components/Stepper/index.js
> +            active={props.steps === index + 1}
Una curiosidad: en la línea 29 estamos haciendo casi lo mismo solo que `index === props.steps - 1`

2021-02-22 06:55 UTC, wixo commented on components/Stepper/styles.js
> +  border: ${({ active, type }) =>
Estamos tratando de mantener el orden de las propiedades en orden alfabético, para que sea más fácil de encontrar en el futuro. `border` iría abajo de `background-color`.

2021-02-23 06:51 UTC, paulclindo commented on components/Stepper/index.js
> +            active={props.steps === index + 1}
> Una curiosidad: en la línea 29 estamos haciendo casi lo mismo solo que `index === props.steps - 1`

Es cierto! Acabo de refactorizarlo 👍

2021-02-23 06:53 UTC, paulclindo commented
@wixo Fixed!

2021-02-24 07:00 UTC, wixo approved these changes
🚀

2021-02-24 07:01 UTC, merged