UI/alert when no candidates found
openpolitica/open-wizard pull request #178
Opened 2021-02-26 06:46 UTC by paulclindo

Closes https://github.com/openpolitica/open-wizard/issues/137

<img src="https://user-images.githubusercontent.com/46382556/109265296-50f5f300-77d4-11eb-86a9-62e16f6ebcf8.png" width="500"/>

2021-02-27 16:41 UTC, wixo requested changes
Hola @paulclindo! gracias, en el deploy de prueba se ve que siempre muestra el chip (este nombre ya quedó 🤷‍♂️) de no resultados aún teniendo resultados, hice pruebas con Lima y peruanos en el extranjero: 
<img width="1280" alt="Screen Shot 2021-02-27 at 10 40 50" src="https://user-images.githubusercontent.com/324686/109393591-a7585400-78f0-11eb-999d-f192f950ab01.png">

Puedes revisarlo?

2021-02-27 16:41 UTC, wixo commented on components/Chip/styles.js
> +  min-height: 1.25rem;
Si tenemos `min-height` o `min-width` debemos mantener `height` o `width`?

2021-02-27 16:41 UTC, wixo commented on components/Steps/PartyResults/index.js
> +        {candidates.length ? (
Es necesario poner todo en un ternario?
podríamos tener:
```
<Styled.Results>{showPartyCards(candidates)}</Styled.Results>
{!candidates.length ?
  <Styled.NoCandidatesChip type={'bad'}>
    <span>Creo que estás pidiendo mucho.</span>
  </Styled.NoCandidatesChip> : 
  null
}
```

2021-02-28 05:41 UTC, paulclindo commented on components/Chip/styles.js
> +  min-height: 1.25rem;
My bad! En realidad lo mejor seria usar un `flex` ya que es parte de un flex container 🙌

2021-02-28 06:12 UTC, paulclindo commented on components/Steps/PartyResults/index.js
> +        {candidates.length ? (
Es igual, no hay diferencias. Es como multiples `if`  y `if else` nested basados en ternaries. IMO lo encuentro mas legible y explicito en estos casos para agrupar posibles resultados, y aparte que no son mas que dos casos.

2021-02-28 06:13 UTC, paulclindo commented
> Hola @paulclindo! gracias, en el deploy de prueba se ve que siempre muestra el chip (este nombre ya quedó 🤷‍♂️) de no resultados aún teniendo resultados, hice pruebas con Lima y peruanos en el extranjero:
> <img alt="Screen Shot 2021-02-27 at 10 40 50" width="1280" src="https://user-images.githubusercontent.com/324686/109393591-a7585400-78f0-11eb-999d-f192f950ab01.png">
> 
> Puedes revisarlo?

@wixo Fixed it! Me equivoque pensando que candidates era un array 😅

2021-03-02 05:29 UTC, wixo requested changes
Hola @paulclindo, gracias, hay unos conflictos de git que podemos corregir y un detalle con el ternario, que solo podría ser 1, gracias!

2021-03-02 05:29 UTC, wixo commented on components/Steps/PartyResults/index.js
> +        ) : !Object.keys(candidates).length ? (
De última sería solo 1 ternario y no 2, en un caso hay un length y en el otro no, no necesitamos el último `: null`, te parece?

2021-03-02 05:29 UTC, wixo commented on components/Steps/PartyResults/index.js
> +          <Styled.NoCandidatesChip type={'bad'}>
Un detalle `type="bad"` en vez de `type={'bad'}`. confieso que a mi se me paso por copiar y pegar el uso de chip 🙈 pero mejor empezar a usar type="bad" ya que no hay ningún cálculo

2021-03-04 01:48 UTC, wixo approved these changes
Muchas gracias @paulclindo!! 🚀

2021-03-04 01:48 UTC, merged