Fix routing and label on back click
openpolitica/open-wizard pull request #197
Opened 2021-03-01 17:46 UTC by AlmeAld

Closes #164 

Demo:
https://www.loom.com/share/2bdb89893b804e288c4b291d144f4b9b

2021-03-02 05:26 UTC, wixo requested changes
Gracias Alme, unos detalles a revisar.

2021-03-02 05:26 UTC, wixo commented on components/Favorites/index.js
> +    Router.push('results/grouped-by-party');
Si vamos a ir por este approach, `onGoBackButtonClick` se hace idéntica a `onKeepLookingButtonClick`, podemos cambiar el nombre a `goBackToPartyResults` y usarlo en las 2 instancias.

2021-03-02 05:26 UTC, wixo commented on components/Steps/CandidateSingle/index.js
> +  function generateLabel(path) {
Esta función podría llamarse `generateGoBackText` que es lo que realmente hace. También, puede vivir fuera del componente `CandidateSingle` así no se crea cada vez que hay nuevo render. (fijarse en `LoadingScreen`)
También no hay necesidad de escribir el else podría ser:
```js
	  if (!ls('op.wizard')) {
      return 'Inicia tu viaje';
    }
    if (path === '/favorites') {
      return 'Posibles opciones';
    }
    return 'Regresa a la Lista';
```

2021-03-03 03:16 UTC, AlmeAld commented on components/Favorites/index.js
> +    Router.push('results/grouped-by-party');
cierto! que distraída, ya realicé el cambio @wixo .

2021-03-04 01:51 UTC, wixo approved these changes
Gracias @AlmeAld!! 🚀

2021-03-04 01:52 UTC, merged