Rearrange buttons in partyResults and CandidateResults
openpolitica/open-wizard pull request #203
Opened 2021-03-05 08:48 UTC by AlmeAld

Closes #194 

![image](https://user-images.githubusercontent.com/60791759/110090581-73a08280-7d65-11eb-8ca9-301638e56319.png)

![image](https://user-images.githubusercontent.com/60791759/110090643-81ee9e80-7d65-11eb-932c-8ece4da0b048.png)

2021-03-06 02:31 UTC, wixo requested changes
Hola @AlmeAld, gracias por enviar este PR, he dejado unos comments sobre unos pequeños detalles, pero muchas gracias por seguir los lineamientos del resto del código 🙌

2021-03-06 02:31 UTC, wixo commented on components/Steps/CandidateResults/index.js
> +              text="Mis posibles opciones"
Como en `components/FavoriteButton/styles.js` estamos usando `import { StyledButton } from 'components/BaseButton/styles'` este prop no está disponible aquí, luego en https://github.com/openpolitica/open-wizard/pull/203/files#diff-0d78eb37392275d0c5bbf294c564093eb2bb8d3b8c0bc35059cdbcce405dcc28R7 estamos de nuevo escribiendo este texto. Recomendaría hacer import de `BaseButton` y luego usar el prop como venimos usándolo en el resto de la App.

2021-03-06 02:31 UTC, wixo commented on components/Steps/CandidateResults/index.js
> +          type="transparent"
Cool trick! jaja

2021-03-06 02:31 UTC, wixo commented on public/images/icons/starBorderGreen.svg
> +<svg width="16" height="16" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M8 1.302L9.654 5.28l.118.282.304.024 4.294.344-3.27 2.803-.232.198.07.297 1 4.19-3.676-2.245L8 11.014l-.26.16-3.677
Un pequeño detalle, aquí según nuestro `.editorconfig` deberíamos de tener un salto de línea (enter) aquí, lo puedes agregar?

2021-03-06 04:11 UTC, AlmeAld commented on components/Steps/CandidateResults/index.js
> +          type="transparent"
jeje :sweat_smile:

2021-03-08 04:19 UTC, wixo requested changes
Gracias @AlmeAld, un comentario sobre abstraer el uso de `SeeFavoritesButton` a su propio componente.

2021-03-08 04:19 UTC, wixo commented on components/Steps/CandidateResults/styles.js
> +export const SeeFavoritesButton = styled((props) => <BaseButton {...props} />)`
por qué no solo
```
styled(BaseButton)`...`
```
?

Aparte el número de reglas css internas al igual que en https://github.com/openpolitica/open-wizard/pull/203/files#diff-92649e2bff1c293aae65bab55f053b7c7c33d30f2a4118fba61919b16b5ffa96R31 me hace pensar que este debería ser su propio componente, que puede ser una extensión de `BaseButton` llamada `BaseIconButton` solo que tiene un prop llamado `icon` como se propone en https://github.com/openpolitica/open-wizard/pull/203/files#diff-189f33131e593419ae5cbb07f5c779dc79abe77c4f2c862114dd912218afeb4dR6, porfa considerar hacer eso

2021-03-09 01:27 UTC, wixo approved these changes
Muchas gracias @AlmeAld!

2021-03-09 01:27 UTC, merged