Mod screen candidate
openpolitica/open-wizard pull request #210
Opened 2021-03-06 21:22 UTC by gianpietro1

Agrega sección de Información personal (falta ícono)
1. Agrega DNI (falta backend al momento del PR)
2. Agrega edad

Otros cambios:
3. Agrega distrito electoral
4. Renombra papeletas
5. Añade campos en pasado político
6. Arregla supresión de Ñs en lodash (ejemplo con candidato 134889)

2021-03-07 00:31 UTC, wixo requested changes
Hola @gianpietro1, gracias por hacer estos cambios, solo unos comentarios respecto a la mantenibilidad del código a futuro y algunos detalles que podrían confundir a futuros developers que vean nombres de variables y así. Y una pregunta sobre si el DNI ya se debería de mostrar en el preview.

2021-03-07 00:31 UTC, wixo commented on components/Accordion/processCandidateContent.js
> +  const lowerRegionArray = text.toLowerCase().split(' ');
No entiendo porque estas variables hacen referencia a _region_ cuando no se usa para esos casos. También tengo la duda de si es necesario tener el _omit_ pattern por aquí, me imagino en algún centro de trabajo queremos algo como: "Hospital del Niño" ? Si es así entonces porfa actualicemos los nombres de estas variables para no confundir a futuro.

2021-03-07 00:31 UTC, wixo commented on components/Accordion/processCandidateContent.js
> +const getAge = (dateString) => {
Pienso que tiene sentido hacer esto aunque también podríamos considerar usar un library de datetime para obviarnos de escribir tanto código.

2021-03-07 00:31 UTC, wixo commented on components/Accordion/processCandidateContent.js
> +          <strong>DNI:</strong> {content.dni}
He notado que no se está mostrando el dni de los candidatos, esto es algo que luego vendrá desde el API? 
<img width="357" alt="Screen Shot 2021-03-06 at 18 20 21" src="https://user-images.githubusercontent.com/324686/110225198-9f785100-7ea8-11eb-90bb-c05778a5bc08.png">

2021-03-07 00:31 UTC, wixo commented on components/Accordion/processCandidateContent.js
> +      if (content.afiliations) {
Pienso que tiene sentido esta lógica por el tipo de código ya escrito en este archivo pero creo que ya estamos llegando al límite de indentation que permite una fácil lectura (generalmente se recomienda hasta 4 niveles), igual pienso que es una regla arbitraria pero también me hace pensar si en un futuro debiéramos considerar un refactor de esto 🤔 Espero que dado los pocos cambios que se esperan ya no necesitemos cambiar tantas cosas por aquí. Este solo es un comentario, no considero que debamos hacer algún cambio aquí.

2021-03-07 00:31 UTC, wixo commented on components/CandidateBigCard/index.js
> +          <Row style={{ flexDirection: 'column' }}>
Podríamos considerar crear un propio styled component?, a primera vista confunder que un componente llamado `Row` tenga dirección `column`, cuando podemos tener un componente llamado `Column` que tenga ese css rule.

2021-03-07 00:31 UTC, wixo commented on components/CandidateBigCard/styles.js
> +`;
Nuestro `.editorconfig` agregaría un salto de línea al final de este archivo, se tiene configurado en tu local?

2021-03-07 00:33 UTC, wixo commented on components/Accordion/processCandidateContent.js
> +  const lowerRegionArray = text.toLowerCase().split(' ');
test

2021-03-07 12:27 UTC, gianpietro1 commented on components/Accordion/processCandidateContent.js
> +  const lowerRegionArray = text.toLowerCase().split(' ');
Olvidé adaptar a este caso, estoy subiendo un cambio que generaliza el término "Region".

Otra opción más dry sería remover lodash de la función startCasePeruvianRegions.js (que se ocupa de las regiones) y volver a importar esa, pero afecta otro lugar del código (oportunidad para carpeta helper functions?)

2021-03-07 12:32 UTC, gianpietro1 commented on components/Accordion/processCandidateContent.js
> +const getAge = (dateString) => {
El grueso del código es, lamentablemente, extraer el día/mes/año para poder convertir a fecha pues la información viene en un string. Al momento no encontré una librería que lo pueda hacer.
Otra opción es pasar el código al backend y devolver sólo la edad.

2021-03-07 12:34 UTC, gianpietro1 commented on components/Accordion/processCandidateContent.js
> +          <strong>DNI:</strong> {content.dni}
Correcto, esta mañana ya apliqué correspondiente en backend. Igual estoy subiendo un nuevo commit porque hace falta agregar ceros (desde el JNE el campo ya viene en número y los ceros se remueven)

2021-03-07 12:36 UTC, gianpietro1 commented on components/Accordion/processCandidateContent.js
> +      if (content.afiliations) {
Ok gracias. Creo que la mayor cantidad de indentations se agrega por poner protecciones en caso de que la información no venga del API, podríamos revisar este código y el de sanciones (que es similar) en el futuro cercano.

2021-03-07 12:49 UTC, gianpietro1 commented on components/CandidateBigCard/index.js
> +          <Row style={{ flexDirection: 'column' }}>
Tiene sentido, fixing...

2021-03-07 12:53 UTC, gianpietro1 commented on components/CandidateBigCard/styles.js
> +`;
Sí, yo había estado grabando sin formato este archivo, fixed.

2021-03-08 02:14 UTC, wixo approved these changes
Gracias @gianpietro1! 🙌

2021-03-08 02:15 UTC, merged