Add big icon button and fix styles
openpolitica/open-wizard pull request #239
Opened 2021-03-18 06:08 UTC by AlmeAld

- Closes #181 
- Closes #179

2021-03-18 06:36 UTC, wixo requested changes
Hola @AlmeAld te dejo unas recomendaciones y preguntas, muchas gracias! 🙌 
Visualmente me parece que el botón Comenzar no está quedando como esperamos.

2021-03-18 06:36 UTC, wixo commented on components/HomePage/index.js
> +    router.push('/');
Ya tenemos en main la primera ruta de presidentes: '/presidential-steps/1`, deberíamos ya usarla.

2021-03-18 06:36 UTC, wixo commented on components/HomePage/index.js
> +        <ContentButtonCandidate>
No me queda claro este nombre, no sería `ButtonsRow` o algo así?

2021-03-18 06:36 UTC, wixo commented on components/HomePage/index.js
> +            <img src="../images/icons/congressmen.svg" alt="icono presidente" />
`alt="icono congresistas"` ?

2021-03-18 06:36 UTC, wixo commented on components/HomePage/index.js
> +            <TextButton>
No sería `ButtonText`?

2021-03-18 06:36 UTC, wixo commented on components/HomePage/index.js
> +              Encontrar mi candidato<SpanCandidate> presidencial</SpanCandidate>
`<SpanCandidate>` no necesita ser un styled component ya que existe un html tag que hace lo mismo `<strong>` y es un poco más semántico que usarlo a nivel de css.

2021-03-18 06:36 UTC, wixo commented on components/HomePage/index.js
> +              Encontrar mi candidato<SpanCandidate> presidencial</SpanCandidate>
También cuidado con los espacios en blanco por favor.

2021-03-18 06:36 UTC, wixo commented on components/HomePage/index.js
> +              Encontrar mi candidato al <SpanCandidate>congreso</SpanCandidate>{' '}
Aquí pienso que debería ser plural porque podemos votar por 2 congresistas. mi candidatos => mis opciones / mis candidatos?

2021-03-18 06:36 UTC, wixo commented on components/HomePage/styles.js
> +  margin: 0px -13px 0px 0px;
Por qué margen negativo?

2021-03-18 06:36 UTC, wixo commented on public/images/icons/congressmen.svg
> +<svg width="70" height="70" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#clip0)" fill="#4EB5A2"><path d="M44.69 42.587a9.019 9.019 0 00-2.115-2.109c-.47-.293-.998-.585-1.527-.878
Agregarle una línea en blanco, como lo haría `.editorconfig`.

2021-03-18 06:36 UTC, wixo commented on components/HomePage/index.js
> +    <Styled.LogoImage>
Por qué tener un nivel de anidación más si desde styles.js podemos hacer `styled(Image)`, revisar otras partes del código donde se hizo eso por favor.

2021-03-18 06:36 UTC, wixo commented on components/HomePage/index.js
> +            <Styled.SpanGreen> {remainingDays} días </Styled.SpanGreen>
No recomiendo ponerle un nombre tan específico porque luego esto puede cambiar a otro color, recomiendo usar `Styled.Emphasis`.

2021-03-18 06:36 UTC, wixo commented on components/HomePage/index.js
> +              <Styled.SpanBlack> congresista</Styled.SpanBlack>
Aquí sería solo `<strong>`.

2021-03-19 00:34 UTC, AlmeAld commented on components/HomePage/styles.js
> +  margin: 0px -13px 0px 0px;
esto lo corregí en el siguiente commit de este PR

2021-03-19 03:11 UTC, AlmeAld commented on components/HomePage/index.js
> +    <Styled.LogoImage>
Me parece que el componente next image necesita un wrapper necesariamente para darle estilos, así como en Componente Chip https://github.com/openpolitica/open-wizard/blob/1ef198aa2b0df62fc61a2f03e08dcd26e14aae75/components/Chip/styles.js#L4 , ya que en los otros no se están aplicando los estilos. como en CandidateBigCard
https://github.com/openpolitica/open-wizard/blob/1ef198aa2b0df62fc61a2f03e08dcd26e14aae75/components/CandidateBigCard/styles.js#L24
![image](https://user-images.githubusercontent.com/60791759/111726329-ba4aae00-8836-11eb-8d2d-88e5b68f577f.png)

2021-03-19 07:07 UTC, wixo commented on components/HomePage/index.js
> +    <Styled.LogoImage>
Me parece que en `TeamCard` sí se da: https://github.com/openpolitica/open-wizard/blob/main/components/TeamCard/styles.js#L4-L8

![Screen Shot 2021-03-19 at 1 06 45](https://user-images.githubusercontent.com/324686/111743496-69937f00-884f-11eb-8bc7-d5fef5961447.png)

Me confirmas porfa.

2021-03-19 19:33 UTC, AlmeAld commented on components/HomePage/index.js
> +    <Styled.LogoImage>
si, toma en cuenta esos dos estilos porque ahí se está manipulando la imagen en si, pero cuando se quiere agregar un border, margin, etc no lo toma en cuenta como figura en el screenshot de TeamCard, para esto sería necesario agregarle un wrapper.

2021-03-21 02:59 UTC, wixo approved these changes
Muchas gracias @AlmeAld!! buen trabajo! 🚀

2021-03-21 03:00 UTC, merged