President/question list UI
openpolitica/open-wizard pull request #246
Opened 2021-03-19 23:39 UTC by paulclindo

Closes: 
https://github.com/openpolitica/open-wizard/issues/189
https://github.com/openpolitica/open-wizard/issues/188
https://github.com/openpolitica/open-wizard/issues/187
https://github.com/openpolitica/open-wizard/issues/184

Pueden empezar el flow desde este link : http://localhost:3000/presidential-steps/1. Por ahora al final les lleva a una pantalla `TODO: results`

2021-03-20 04:58 UTC, wixo requested changes
Hola @paulclindo! gracias por enviar esto, noto la intención de reducir la complejidad y se agradece el esfuerzo. Dejo algunos comments y preguntas, igual tengo esta pregunta grande que en desktop se está viendo de forma "fluida", que va en detrimento de como se ven los pasos anteriores, entonces no sé si podemos corregirlo en este PR también.

También: noto que se pueden omitir todas las respuestas, recuerdo que hay un máximo de respuestas que se pueden omitir para dar un resultado, pero necesito confirmación. cc: @redsii

2021-03-20 04:58 UTC, wixo commented on components/BaseRadioButton/styles.js
> +export const Input = styled.input`
```suggestion
export const Input = styled('input').attrs({ type: 'radio' })`
```
Sería cool que se llame RadioInput pero el nombre ya está tomado arriba, y me pregunto por qué necesitaría existir el otro `RadioInput` si es solo un wrapper que agrega flex, pienso que puede ser por qué el padre es grid, pero no sé, hay una explicación?

2021-03-20 04:58 UTC, wixo commented on components/BaseRadioButton/index.js
> +    <Styled.Radio>
Un overwrite de estilos no debería venir desde aquí?
```suggestion
    <Styled.Radio {...inputProps} >
```

2021-03-20 04:58 UTC, wixo commented on components/BaseRadioButton/RadioGroup.js
> +      <div role="radiogroup">{children}</div>
Gracias por que querer seguir las recomendaciones de a11y, creo que es la gran tech debt de esta app en general, pero esto no crea varios role="radiogroup"s cuando solo queremos 1 por página?

![Screen Shot 2021-03-19 at 22 12 56](https://user-images.githubusercontent.com/324686/111858679-57254e00-8900-11eb-9c9a-469f717720ec.png)

2021-03-20 04:58 UTC, wixo commented on components/BaseRadioButton/styles.js
> +export const Radio = styled.label`
Qué te parece usar una forma más functional y dejarlo así:
```suggestion
export const Radio = styled('label')`
```
Sé que técnicamente son lo mismo, pero pasar de styled.label a styled(Label) es otro modelo mental. Solo una recomendación.

2021-03-20 04:58 UTC, wixo commented on hooks/useTopics/index.js
> +    } else {
Los `else` son difíciles de leer si dentro del `if` hay varias líneas, no pienso que sea el caso, pero ya que estamos retornando, no sería lógicamente válido escribir `if (answerIndex !== -1) { ... return }`

2021-03-20 04:58 UTC, wixo commented on components/PresidentialQuestion/index.js
> +const nameCapitalized = (string) =>
Me pregunto si esto es correcto en Inglés, dado que la primera regla es <adj><noun> sería: `capitalizedName`.

2021-03-20 04:58 UTC, wixo commented on components/PresidentialQuestion/index.js
> +      router.push('/results/presidential');
Qué te parece la ruta `/presidential-results/grouped-by-compatibility`? ya que hasta ahora tenemos `/presidential-steps/` y `/results/grouped-by-party`. solo `results` debería pasar a llamarse `congress-results` idealmente.

2021-03-20 04:58 UTC, wixo commented on components/PresidentialQuestion/index.js
> +
Queremos mantener este espacio en blanco?

2021-03-20 04:58 UTC, wixo commented on components/PresidentialQuestion/index.js
> +    <Fragment>
Gracias por usar `<Fragment>` en vez de `<>` jaja

2021-03-20 04:58 UTC, wixo commented on components/PresidentialQuestion/index.js
> +  const handlePreviousButton = () => {
Pienso que esta como `handleNextButton` podrían ser funciones puras (dependency injection con todos sus argumentos) para que vivan fuera del re-render y se puedan (idealmente) escribir tests en un futuro, pero también sería más trabajo. Pienso que por ahora es good enough.

2021-03-20 04:58 UTC, wixo commented on components/PresidentialQuestion/index.js
> +                  onChange={(value) => {
Nos podríamos ahorrar los `{}` de la función? por más que `setSelectedOption` no retorne algo válido para la operación.

2021-03-20 04:58 UTC, wixo commented on components/PresidentialQuestion/index.js
> +                disabled={selectedOption === ''}
Cuando no hay una opción seleccionada este botón tiene estilos como si se pudiese hacer click.

![Screen Shot 2021-03-19 at 22 39 18](https://user-images.githubusercontent.com/324686/111859166-758d4880-8904-11eb-9616-f2c938dc43d6.png)

2021-03-20 04:58 UTC, wixo commented on components/PresidentialQuestion/styles.js
> +  text-decoration: underline;
Preferiría que solo en hover tenga el underline, pienso que es una falla de diseño tener un Botón que se comporte como un texto, creo que también tenemos `LinkButton` que no fue muy reusado.

2021-03-20 04:58 UTC, wixo commented on components/PresidentialQuizBreakdown/index.js
> +  const { userSelectedTopics, addQuizItems } = useTopics();
👍

2021-03-20 04:58 UTC, wixo commented on components/BaseRadioButton/styles.js
> +export const RadioLabel = styled.span`
Le pondríamos un `cursor: pointer` para hacerle saber al usuario en desktop que es un elemento clickeable? todos los otros elementos clickeables de la app lo tienen (o idealmente deberían)

2021-03-20 06:31 UTC, wixo commented on pages/results/presidential/index.js
> +const nossrPresidentQuestion = () => (
```suggestion
const nossrPresidentialResults = () => (
```

2021-03-20 06:31 UTC, wixo commented on pages/results/presidential/index.js
> +export default nossrPresidentQuestion;
```suggestion
export default nossrPresidentialResults;
```

2021-03-20 18:07 UTC, paulclindo commented on components/BaseRadioButton/RadioGroup.js
> +      <div role="radiogroup">{children}</div>
El aria role Radiogroup es para identificar un `div` como container de radio buttons, asi que si es necesario

2021-03-20 18:07 UTC, paulclindo commented on components/PresidentialQuestion/index.js
> +const nameCapitalized = (string) =>
Ambas son validas, like `listSorted`

2021-03-20 18:07 UTC, paulclindo commented on components/PresidentialQuestion/index.js
> +      router.push('/results/presidential');
Ok ahora lo cambio

2021-03-20 18:07 UTC, paulclindo commented on components/PresidentialQuestion/index.js
> +                disabled={selectedOption === ''}
Oh vi en un PR anterior que le agregaron disable, ahora lo reviso

2021-03-20 18:07 UTC, paulclindo commented on pages/results/presidential/index.js
> +const nossrPresidentQuestion = () => (
Good catch!

2021-03-20 19:02 UTC, paulclindo commented on components/BaseRadioButton/index.js
> +    <Styled.Radio>
Me puse en el caso que quisiéramos manejar el radio button standalone, y facil le pasen propiedades como `onChange`, `checked`,  etc

2021-03-20 19:03 UTC, paulclindo commented on components/BaseRadioButton/styles.js
> +export const Input = styled.input`
Es mas que nada para entender que RadioInput esta basado en Input y el RadioControl, y que el input se esta ocultando 🙌

2021-03-20 20:08 UTC, paulclindo commented
@wixo Acerca del layout, voy a arreglar para los presidential pages por ahora y luego enviar otro PR en toda la app. Porque se haría grande el PR 🙌

2021-03-21 02:28 UTC, wixo commented on components/BaseRadioButton/RadioGroup.js
> +      <div role="radiogroup">{children}</div>
es decir `role="radiogroup"` no debería ir a nivel del div que los contiene `<div class="sc-gTgzIj fTLLNh" role="radiogroup">`?

2021-03-21 02:48 UTC, wixo requested changes
Solo unos pequeños detalles, pienso que está quedando listo 🙌 y la pregunta anterior sobre `radiogroup`s.

2021-03-21 02:48 UTC, wixo commented on components/PresidentialQuestion/index.js
> +const ALLOW_OMITTED_QUESTIONS_PER_TOPIC = 1;
Personalmente no soy muy fan de tener "constantes" en este case, semánticamente no transmite nada, pero igual dejo al criterio que otras "constantes" que guardan variables de configuración están en camelCase y/o en `next.config.js`

2021-03-21 02:48 UTC, wixo commented on components/layouts/MainLayout/index.js
> +    <div>
Este `div` puede ser un `Fragment`?

2021-03-21 18:12 UTC, paulclindo commented on components/BaseRadioButton/RadioGroup.js
> +      <div role="radiogroup">{children}</div>
No, claro que no. Es por grupo de radio buttons asociados, en este caso esta relacionados por pregunta

2021-03-21 18:35 UTC, paulclindo commented on components/PresidentialQuestion/index.js
> +const ALLOW_OMITTED_QUESTIONS_PER_TOPIC = 1;
No tengo preferencias en esto,  puede ser capital-named or camel-case constants pero si me parece que luego deberíamos agregar un lint check para automatizar los nits changes que tenemos en el codebase 🙏

2021-03-21 18:35 UTC, paulclindo commented on components/layouts/MainLayout/index.js
> +    <div>
Si, cualquiera estaría bien. Pero ya que no tenemos algún estilo aplicado o semántica lo cambio a Fragment 👌

2021-03-21 18:39 UTC, paulclindo commented
@wixo Fixed it 👍

2021-03-21 21:08 UTC, wixo approved these changes
Gracias @paulclindo! 🚀

2021-03-21 21:10 UTC, merged

2021-03-21 21:37 UTC, redsii commented on components/PresidentialQuestion/index.js
> +const nameCapitalized = (string) =>
Me parece capitalizedName! Creo que es un toquesin mas intuitivo a leer.