sort topics
openpolitica/open-wizard pull request #250
Opened 2021-03-20 18:39 UTC by paulclindo

2021-03-20 18:53 UTC, wixo commented
Ahora son 8 topics, :D

![Screen Shot 2021-03-20 at 12 52 40](https://user-images.githubusercontent.com/324686/111882433-29c9b600-897b-11eb-9fda-f09a2a46f291.png)

2021-03-21 02:17 UTC, wixo requested changes
Gracias @paulclindo, solo unos detalles. 🙌

2021-03-21 02:17 UTC, wixo commented on components/BaseQuizBreakdownItem/styles.js
> +  color: #475065;
Podemos tener las reglas ordenadas alfabéticamente? dado que es un proceso manual estoy considerando que agreguemos esto al `eslint`: https://github.com/tinloof/eslint-plugin-better-styled-components cc: @LuighiV

2021-03-21 02:17 UTC, wixo commented on public/images/icons/topics/education.svg
> +<svg width="46" height="46" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="m3.45 20.08.022-.044-.022.044 5.98 2.959v4.916c0 .434.242.831.624 1.02l11.492 5.686c.15.074.314.113.48.113h1.931c.1
Podemos agregar un salto de línea al final del archivo? `.editorconfig` nos ayuda a que esto suceda cada vez que guardamos. Igual para todos los svgs de este `diff`.

2021-03-21 02:39 UTC, LuighiV commented on components/BaseQuizBreakdownItem/styles.js
> +  color: #475065;
okas, ahí lo veo para agregarlo

2021-03-21 03:11 UTC, LuighiV commented on components/BaseQuizBreakdownItem/styles.js
> +  color: #475065;
ya se encuentra como PR en #251

2021-03-21 18:40 UTC, paulclindo commented
@wixo Fixed it !

2021-03-21 21:11 UTC, merged