Added new votu logo
openpolitica/open-wizard pull request #259
Opened 2021-03-22 05:11 UTC by dmarquinah

Se agregó el logo de "Votu.pe" en el header.
Se modificaron los estilos para corregir la redirección a "/" solo haciendo clic en el logo de Votu, quitando el pointer en todo el header.

2021-03-22 06:25 UTC, wixo requested changes
Algo mínimo @dmarquinah, también aprovecho en crear un mirror que apunte al embed. Gracias 🙌

2021-03-22 06:25 UTC, wixo commented on components/Header/index.js
> +        <LogoImg src={'/images/icons/votu_pe_logo.svg'} />
```suggestion
        <LogoImg src="/images/icons/votu_pe_logo.svg" />
```
Es raro creo que es el único asset que tiene `_` en su nombre. Podemos aprovechar en actualizarlo a `-`?

2021-03-23 23:31 UTC, dmarquinah commented on components/Header/index.js
> +        <LogoImg src={'/images/icons/votu_pe_logo.svg'} />
Hecho, agregué un commit https://github.com/openpolitica/open-wizard/pull/259/commits/8feebbac90e548b9a9fb0748b4b2f39f529836c1

2021-03-24 05:37 UTC, wixo approved these changes
gracias @dmarquinah!! 🚀

2021-03-24 05:37 UTC, merged