Add resetTopic to reset previous answers
openpolitica/open-wizard pull request #267
Opened 2021-03-23 23:13 UTC by LuighiV

Adiciona resetTopic cuando regresa a la página principal, evitando que se almacenen respuestas anteriores e ingrese al cálculo de compatibilidad.

2021-03-23 23:18 UTC, paulclindo approved these changes, later dismissed

2021-03-24 00:24 UTC, wixo requested changes
Gracias @LuighiV, solo 2 cosas 🙌

2021-03-24 00:24 UTC, wixo commented on hooks/useTopics/index.js
> +        resetTopics: (value) => dispatch({ type: 'resetTopics' }),
En este caso no usamos un `value` ya que la acción es hacer un reset. Medio extraño que no te haya dicho nada el `eslint`. 🤔 
```suggestion
        resetTopics: () => dispatch({ type: 'resetTopics' }),
```

2021-03-24 00:24 UTC, wixo commented on components/PresidentialResults/index.js
> +    const handlePreviousButton = () => {
Está función puede ser declarada líneas arriba, como por la 36, te parece? También podría llamarse `handleGoBackButton` ya que así se llama el Componente que la usa.

2021-03-24 00:30 UTC, LuighiV commented on hooks/useTopics/index.js
> +        resetTopics: (value) => dispatch({ type: 'resetTopics' }),
okas... bueno me base en otro script de favoritos y lo dejé así... ahora lo corrijo :)

2021-03-24 00:30 UTC, LuighiV commented on components/PresidentialResults/index.js
> +    const handlePreviousButton = () => {
okas, sí tiene mas sentido... ahora lo hago

2021-03-24 00:35 UTC, juanpres commented on hooks/useTopics/index.js
> +        resetTopics: (value) => dispatch({ type: 'resetTopics' }),
Tienes razón, se nos paso en Favoritos jaja, 🥲

2021-03-24 00:38 UTC, LuighiV commented on components/PresidentialResults/index.js
> +    const handlePreviousButton = () => {
Un detalle, también me he dado cuenta que el texto del botón para las preguntas dice "Regresar" en cambio este botón dice "Regresa"... eso está bien?

2021-03-24 01:22 UTC, wixo commented on components/PresidentialResults/index.js
> +    const handlePreviousButton = () => {
En los wireframes dice "Regresar" y en el figma de ui dice "Regresa", 🤷‍♂️ . Todas las demás instancias en la app dicen "Regresa" por ahora así que vamos con eso. Pareciera que las preguntas deben de actualizarse.

2021-03-24 01:26 UTC, LuighiV commented on components/PresidentialResults/index.js
> +    const handlePreviousButton = () => {
entiendo... ya sería otro issue

2021-03-24 01:27 UTC, LuighiV commented on components/PresidentialResults/index.js
> +    const handlePreviousButton = () => {
ya he subido el cambio que sugeriste en #958938b

2021-03-24 02:00 UTC, wixo approved these changes
gracias @LuighiV! 🙌

2021-03-24 02:21 UTC, merged