Añadir información en la selección de tópicos sobre un análisis de solo 10 primeros
openpolitica/open-wizard pull request #308
Opened 2021-03-29 23:41 UTC by LuighiV

Se agrega el mensaje 
*Solo mostraremos los 10 partidos con mayor intención de voto presidencial al 10 de marzo de 2021.
De acuerdo con https://www.figma.com/file/NcTbjOqejUTk74m7mMyGmZ/VOTU_Wireframes?node-id=657%3A0

2021-03-29 23:43 UTC, LuighiV commented
#291

2021-03-31 03:32 UTC, wixo requested changes
Hola @LuighiV, 2 preguntas, muchas gracias!

2021-03-31 03:32 UTC, wixo commented on components/PresidentialTopics/index.js
> +          <Styled.Strong>
esto no podría ser solo el html tag `<strong>`?

2021-03-31 03:32 UTC, wixo commented on components/InfoMessage/styles.js
> +export const InfoMessage = styled('p')`
No se puede partir de `styled(BaseParagraph)`?

2021-03-31 03:38 UTC, LuighiV commented on components/PresidentialTopics/index.js
> +          <Styled.Strong>
creo que sí, de hecho lo puse inicialmente, solo que me puse en el caso se quisiera añadir otra propiedad al strong

2021-03-31 03:40 UTC, LuighiV commented on components/InfoMessage/styles.js
> +export const InfoMessage = styled('p')`
si, aunque tiene varias características que varían de base paragraph en color y en tamaño. Creo que lo puedo cambiar para que parta de BaseParagraph

2021-03-31 04:07 UTC, wixo approved these changes
Gracias @LuighiV! 🙌

2021-03-31 04:08 UTC, merged