Propuesta para actualizar título el día de las elecciones y cuando estas finalicen
openpolitica/open-wizard pull request #336
Opened 2021-04-10 18:31 UTC by LuighiV

Propuesta incluye:
- Actualizar el tiempo a la zona horaria actual
- Considerar las horas restantes.
- Cambio de mensaje cuando es el día de las elecciones y después de estas.
Closes #335

2021-04-10 21:16 UTC, wixo requested changes
Gracias Luighi! 🙌

2021-04-10 21:16 UTC, wixo commented on components/HomePage/index.js
> +          Gracias por usar <strong>Votu</strong>, nos estamos preparando para
Solo considerar usar siempre Votu.pe

2021-04-11 00:05 UTC, LuighiV commented on components/HomePage/index.js
> +          Gracias por usar <strong>Votu</strong>, nos estamos preparando para
Cambiado en bfdbf60

2021-04-11 00:11 UTC, wixo approved these changes

2021-04-11 00:12 UTC, merged